title: Nitika Shrivastava
logo: /assets/img/logo.png
description: Data scientist enthusiast
show_downloads: true
google_analytics:

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/nitika-shrivastava-08343712a/">LinkedIn</a> |
  <a href="https://github.com/NitikaS21">GitHub</a>
  
  <br>   
  Working in IBM for 1 year.
  <br>
  </p>



theme: jekyll-theme-minimal
